### ISSUE TITLE
Is it possible to run the code using 3070 with cuda 11.4?

### ISSUE THREAD

**Issue by Colin-KelinLi** [Gorilla-Lab-SCUT/AffordanceNet#12]
Hi there, I am running the code using NVIDIA 3070 and cuda 11.4. I encountered the following issue when I run the command `python setup.py build_ext --inplace` in `./models/pointnet2_ops`. 

![Screenshot 2023-04-10 17:58:27](https://user-images.githubusercontent.com/24929885/230951763-b6e2206d-b150-4b5c-91b9-86c1adb97a47.png)

I can run it on another device with 2080 and cuda 10.2. I guess this issue is caused by the incompatibility of the device. Is it possible to run it on 3070 devices? 

Thank you!

**Comment by normajeane-m** [comment]
Did you solve the problem?
@Colin-KelinLi

**Comment by Colin-KelinLi** [comment]
@normajeane-m Yes I solved this issue. Please check this https://github.com/facebookresearch/votenet/issues/108

**Comment by normajeane-m** [comment]
@Colin-KelinLi Thanks!
