### ISSUE TITLE
error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by mxmdpc** [Gorilla-Lab-SCUT/AffordanceNet#3]
Hi, When I execute "python setup.py build_ext --inplace" there is one error like follow picture, Is it because the g++ version is different?
![微信图片_20210414154121](https://user-images.githubusercontent.com/71645197/114672977-4ff33380-9d38-11eb-87f7-735f8e10e663.png)

**Comment by cdpmxm** [comment]
https://github.com/Gorilla-Lab-SCUT/AffordanceNet/issues

**Comment by cdpmxm** [comment]
![Uploading 微信图片_20210414154121.png…]()

**Comment by AndlollipopDE** [comment]
maybe a pytorch version issue, if you are not using pytorch 1.0.1, you may need to modify the source code a little bit.

**Comment by mxmdpc** [comment]
Thank U. It Worked.
