### ISSUE TITLE
error：command  ‘gcc’ failed with exit status 1

### ISSUE THREAD

**Issue by tlqwd** [Gorilla-Lab-SCUT/AffordanceNet#4]
Hi, When I execute "python setup.py build_ext --inplace" there is one error like follow picture, I want to know why it happened
![2JYIP4RRJKO9%QK1)C718EP](https://user-images.githubusercontent.com/80080551/115846321-5d08d480-a454-11eb-9ece-39e590596530.png)

**Comment by AndlollipopDE** [comment]
Use the pytorch version described in the requirement.txt

**Comment by tlqwd** [comment]
thanks，it worked
